-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 19:42:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Area` ;

CREATE TABLE IF NOT EXISTS `Area` (
  `sigla` VARCHAR(10) GENERATED ALWAYS AS () VIRTUAL,
  `nome` VARCHAR(45) NOT NULL,
  `superArea` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC) VISIBLE,
  PRIMARY KEY (`sigla`),
  INDEX `fk_Area_Area_idx` (`superArea` ASC) VISIBLE,
  CONSTRAINT `fk_Area_Area`
    FOREIGN KEY (`superArea`)
    REFERENCES `Area` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Curso` ;

CREATE TABLE IF NOT EXISTS `Curso` (
  `sigla` VARCHAR(10) GENERATED ALWAYS AS () VIRTUAL,
  `nome` VARCHAR(45) NOT NULL,
  `horas` TIME NOT NULL,
  `custo` FLOAT NOT NULL,
  `area` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`sigla`),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC) VISIBLE,
  INDEX `fk_Curso_Area1_idx` (`area` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Area1`
    FOREIGN KEY (`area`)
    REFERENCES `Area` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Modulo` ;

CREATE TABLE IF NOT EXISTS `Modulo` (
  `sigla` VARCHAR(10) GENERATED ALWAYS AS () VIRTUAL,
  `nome` VARCHAR(45) NULL,
  `curso` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`sigla`),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC) VISIBLE,
  INDEX `fk_Modulo_Curso1_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_Modulo_Curso1`
    FOREIGN KEY (`curso`)
    REFERENCES `Curso` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Topico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Topico` ;

CREATE TABLE IF NOT EXISTS `Topico` (
  `sigla` VARCHAR(10) GENERATED ALWAYS AS () VIRTUAL,
  `nome` VARCHAR(45) NOT NULL,
  `horas` TIME NOT NULL,
  `modulo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`sigla`),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC) VISIBLE,
  INDEX `fk_Topico_Modulo1_idx` (`modulo` ASC) VISIBLE,
  CONSTRAINT `fk_Topico_Modulo1`
    FOREIGN KEY (`modulo`)
    REFERENCES `Modulo` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluno` ;

CREATE TABLE IF NOT EXISTS `Aluno` (
  `CPF` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `sexo` CHAR NOT NULL,
  `dataNasc` DATE NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Matricula` ;

CREATE TABLE IF NOT EXISTS `Matricula` (
  `data` DATE NOT NULL,
  `pago` TINYINT NOT NULL,
  `aluno` VARCHAR(11) NOT NULL,
  `curso` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`aluno`, `curso`),
  INDEX `fk_Matricula_Aluno1_idx` (`aluno` ASC) VISIBLE,
  INDEX `fk_Matricula_Curso1_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`aluno`)
    REFERENCES `Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Curso1`
    FOREIGN KEY (`curso`)
    REFERENCES `Curso` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Professor` ;

CREATE TABLE IF NOT EXISTS `Professor` (
  `CPF` VARCHAR(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_Professor_Curso1_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Curso1`
    FOREIGN KEY (`curso`)
    REFERENCES `Curso` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
